channels:
  - pytorch
  - anaconda
  - conda-forge
dependencies: # TODO add fairseq, sentencepiece, etc.
  - python=3.7.5
  - nltk==3.4.5
  - python-dotenv==0.15.0
  - marshmallow==3.10.0
  - pytorch==1.8.1
  - pyyaml==5.3.1
  - pika>=1.1.0
