channels:
  - pytorch
  - anaconda
  - conda-forge
dependencies:
  - python==3.9.7
  - nltk==3.5
  - marshmallow==3.8.0
  - pytorch==1.10.0
  - torchvision==0.11.1
  - torchaudio==0.10.0
  - cpuonly==2.0
  - pyyaml==5.3.1
  - pika==1.2.0
  - git
  - pip
  - pip:
      - git+https://github.com/TartuNLP/fairseq.git@mtee-0.1.0
      - sentencepiece==0.1.96