language_pairs:
  - source: de
    target: et
  - source: en
    target: et
  - source: ru
    target: et
  - source: et
    target: de
  - source: et
    target: en
  - source: et
    target: ru
input_types:
  plain: true
  document: true
  web: true
  asr: true
domains:
  - general
parameters:
  modular: True
  with_alignment: true
  checkpoint_path: models
  spm_prefix: models/sp-model