language_pairs:
  - source:
    target:
input_types:
  plain: true
  document: true
  web: true
  asr: true
domains:
  - general
  - legal
  - military
  - crisis
parameters:
  checkpoint_path: models
  spm_model: models/spm.model